[window]
padding = { x = 5, y = 5 }
opacity = 0.7

[scrolling]
history = 500

[font]
size = 13

[font.normal]
family = "Adwaita Mono"
style = "regular"

[font.bold]
family = "Adwaita Mono"
style = "bold"

[font.italic]
family = "Adwaita Mono"
style = "italic"

[font.bold_italic]
family = "Adwaita Mono"
style = "bold_italic"

[colors.primary]
background = "#000000"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"
